### ISSUE TITLE
Sitenin güncellenmesi

### ISSUE THREAD

**Issue by sadikkuzu** [msgsumatematik/msgsumatematik.github.io#1]
https://msgsumatematik.github.io/ sitemizin minimal efor ile güncel hale getirilmesi

Bu repodaki ilgili html dosyaları güncellemek yeterli olacaktır.

**Comment by sadikkuzu** [comment]
Geliştirmeleri https://github.com/msgsumatematik/msgsumatematik.github.io/tree/1-sitenin-g%C3%BCncellenmesi branch üzerinden yapar, sonrasında da main branch'e PR açarız.

**Comment by musolee1** [comment]
Tasarım olarak ilk aşamada, sizce nasıl? Yorumu olan olur mu?

<img width="604" alt="image" src="https://github.com/msgsumatematik/msgsumatematik.github.io/assets/82845054/68ca7d6e-fa6e-4902-8012-1373910d76e0">

**Comment by yusufelyldrm** [comment]
gayet güzel gözüküyor , elinize sağlık.

**Comment by habipakyol** [comment]
Tasarımda ne aşamadayız? Desteğe ihtiyaç var mı?

**Comment by musolee1** [comment]
Selam Habib, sadece hafta sonları bakabiliyorum, iletişim sayfası için de şöyle bir taslak oluşturmuştum. Bunun haricinde ekstra bir bölüm eklemedim. Vaktin varsa elbette tasarıma el atabilirsin :) Ortak sayfada çalışmamız daha iyi olur gibi, benim tasarım yaptığım Figma dosyası [burada](https://www.figma.com/file/VbuGSyTM90nxgjhmmQdhpy/MSGS%C3%9C?type=design&node-id=0-1&mode=design&t=PLJO2ZNftdVXdfjF-0)

![image](https://github.com/msgsumatematik/msgsumatematik.github.io/assets/82845054/bef6482d-60e5-4d5c-bd10-17a9923fe45b)
